name: Run Gradle on PRs

on: pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v2.1.0
      with:
        distribution: adopt
        java-version: 8
    - uses: eskatos/gradle-command-action@v1
      name: gradle build
      with:
        arguments: build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2.2.3
      with:
        name: Package
        path: build/libs
    - uses: eskatos/gradle-command-action@v1
      name: gradle test
      with:
        arguments: test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
