name: Run Gradle on PRs

on: pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 8
    - uses: eskatos/gradle-command-action@v2
      name: gradle jar
      with:
        arguments: jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v2.3.1
      with:
        name: Package
        path: build/libs
    - uses: eskatos/gradle-command-action@v2
      name: gradle test
      with:
        arguments: check
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
