name: Run Gradle test

on:
  push:
    branches:
      - master
      - releases/*

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: adopt
        java-version: 8
    - uses: eskatos/gradle-command-action@v2
      name: gradle check
      with:
        arguments: check jacocoTestReport
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Coveralls Test Report
      run: ./gradlew coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
        CI_NAME: Github Actions
        CI_BRANCH: ${{github.ref}}
        CI_PULL_REQUEST: ${{github.event.pull_request.html_url}}