name: Run Gradle test

on:
  push:
    branches:
      - master
      - releases/*

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: eskatos/gradle-command-action@v1
      name: gradle test
      with:
        arguments: test jacocoTestReport
    - name: Coveralls Test Report
      run: ./gradlew coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{secrets.COVERALLS_REPO_TOKEN}}
        CI_NAME: Github Actions
        CI_BRANCH: ${{github.ref}}
        CI_PULL_REQUEST: ${{github.event.pull_request.html_url}}